[package]
name = "ants"
version = "0.1.0"
edition = "2021"

[profile.dev.package.'*']
opt-level = 3

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
panic = "abort"

[dependencies]
glam = "0.24.0"
macroquad = "0.3"
rstar = "0.10.0"